name: SQL Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    env:
      BUILD_ARGS: ${{ matrix.os_build_args }}
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            os_build_args: -x doctest -x integTest -x jacocoTestReport
    runs-on: ${{ matrix.os }}

    steps:
    - name: Change line endings for windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: git config --global core.autocrlf true
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    
    - name: Build with Gradle
      run: ./gradlew --continue build assemble ${{ env.BUILD_ARGS }}

    - name: Run backward compatibility tests
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: ./scripts/bwctest.sh

    - name: Create Artifact Path
      run: |
        mkdir -p opensearch-sql-builds
        cp -r ./plugin/build/distributions/*.zip opensearch-sql-builds/

    # This step uses the codecov-action Github action: https://github.com/codecov/codecov-action
    - name: Upload SQL Coverage Report
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v3
      with:
        flags: sql-engine
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: opensearch-sql-${{ matrix.os }}
        path: opensearch-sql-builds

    - name: Upload test reports
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          sql/build/reports/**
          ppl/build/reports/**
          core/build/reports/**
          common/build/reports/**
          opensearch/build/reports/**
          integ-test/build/reports/**
          protocol/build/reports/**
          legacy/build/reports/**
          plugin/build/reports/**
